model_list:
  - model_name: "bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0"
    litellm_params:
      model: "bedrock/converse/anthropic.claude-3-5-sonnet-20241022-v2:0"
      aws_region_name: "us-west-2"
      aws_role_name: os.environ/AWS_ROLE_NAME
      aws_session_name: os.environ/AWS_SESSION_NAME

  - model_name: "bedrock/anthropic.claude-3-5-haiku-20241022-v1:0"
    litellm_params:
      model: "bedrock/converse/anthropic.claude-3-5-haiku-20241022-v1:0"
      aws_region_name: "us-west-2"
      aws_role_name: os.environ/AWS_ROLE_NAME
      aws_session_name: os.environ/AWS_SESSION_NAME

  - model_name: "deepseek/*"
    litellm_params:
      model: "deepseek/*"
      api_key: os.environ/DEEPSEEK_API_KEYS

  - model_name: "openai/*"
    litellm_params:
      model: "openai/*"
      api_key: os.environ/OPENAI_API_KEYASD

  - model_name: "anthropic/*"
    litellm_params:
      model: "anthropic/*"
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: "bedrock/*"
    litellm_params:
      model: "bedrock/converse/*"
      aws_role_name: os.environ/AWS_ROLE_NAME
      aws_session_name: os.environ/AWS_SESSION_NAME

  - model_name: "groq/*"
    litellm_params:
      model: "groq/*"
      api_key: os.environ/GROQ_API_KEY

  - model_name: "gemini/*"
    litellm_params:
      model: "gemini/*"
      api_key: os.environ/GEMINI_API_KEY

litellm_settings:
  # set_verbose: True  # Uncomment this if you want to see verbose logs; not recommended in production
  drop_params: True
  num_retries: 3
  request_timeout: 600
  telemetry: False
